### PR TITLE
make redis tests work

### PR DESCRIPTION
**Pull request by lperson**
# Fixes # (issue)

## Description

_Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change, and any blockers that make your change a WIP_

# Checklist:

- [ ] I have manually tested my changes on desktop and mobile
- [ ] The test suite passes locally with my changes
- [ ] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [ ] [My change is 300 lines of code or less](https://github.com/StateVoicesNational/Spoke/blob/main/CONTRIBUTING.md#submitting-your-pull-request), or has a documented reason in the description why it’s longer
- [ ] I have made any necessary changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] My PR is labeled [WIP] if it is in progress

### CODE REVIEW

**Comment by engelhartrueben** [comment]
Hey Larry,

Just want to first thank you for working on this! Absolute life saver!

~~I did get this all to pass locally (w/ NGPVAN) in two ways:~~
~~1. by setting the `jest.setTimeout` to 25,000ms in `__test__/setup.js`. This NGPVAN test looks to take around 20 seconds while running all the other tests alongside it, so some headroom was necessary.~~
~~2. by running `__test__/extensions/contact-loaders/ngpvan/ngpvan.test.js` by itself w/ the original timeout.~~

~~It seems this was extended in the past for one of the campaign tests from the default 5,000ms to 15,000ms.~~

~~Would it be viable to only allow the timeout extension for just the the NGPVAN test? Or could we comfortably extend it globally?~~

~~I understand it may not be best practice to just extend the timer without finding the root cause, so just exploring options!~~

**Review by mau11 — APPROVED** [review]
lgtm!

**Comment by engelhartrueben** [comment]
If you have a second @mau11 , my last commit needs to be removed. No point in extending the jest timeout since that was never the problem. I can get to it later tonight if not!

**Comment by lperson** [comment]
@engelhartrueben I changed the timeout back to 15000

**Comment by engelhartrueben** [comment]
🎉🎉🎉

**Pull request merged**
