### PR TITLE
Dynamic Replies Feature - by MoveOn

### PR DESCRIPTION
**Pull request by mau11**
# Fixes # (issue)

## Description

Merged Spoke v14 + existing 14.1 updates to MoveOn's PR #2365 

# Checklist:

- [ ] I have manually tested my changes on desktop and mobile
- [ ] The test suite passes locally with my changes
- [ ] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [ ] [My change is 300 lines of code or less](https://github.com/StateVoicesNational/Spoke/blob/main/CONTRIBUTING.md#submitting-your-pull-request), or has a documented reason in the description why it’s longer
- [ ] I have made any necessary changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] My PR is labeled [WIP] if it is in progress

### CODE REVIEW

**Comment by engelhartrueben** [comment]
@mau11 please let me know when this is ready for review! I know there has been issues with Redis - so please let me know if/how I can support (:

**Comment by mau11** [comment]
> @mau11 please let me know when this is ready for review! I know there has been issues with Redis - so please let me know if/how I can support (: 

Thanks! It's ready

**Comment by engelhartrueben** [comment]
Hi @mau11!

I have been playing around with this locally, and all looks pretty good. The only thing I will want to double check (probably after we merge this into `stage-main-14.1` is that opt out language still persists, since that seems to be toyed with a bit. 

I feel fairly confident merging this into `14.1` for further testing! We will need to check a lot of the styling, as I think that got messed up in one of the updates, specifically the "add" button 
image
now floating in the top left when it should be bottom right

**Review by engelhartrueben — APPROVED** [review]
🎉

**Pull request merged**
