### PR TITLE
13.2.0 release

### PR DESCRIPTION
**Pull request by crayolakat**
PRs:
- https://github.com/StateVoicesNational/Spoke/pull/2250
- https://github.com/StateVoicesNational/Spoke/pull/2274
- https://github.com/StateVoicesNational/Spoke/pull/2300
- https://github.com/StateVoicesNational/Spoke/pull/2305
- https://github.com/StateVoicesNational/Spoke/pull/2306
- https://github.com/StateVoicesNational/Spoke/pull/2308

### CODE REVIEW

**Comment by crayolakat** [comment]
@Arique1104 Note that the changes in this PR have passed QA and have been running on MoveOn's production env with no errors!

**Review by Arique1104 — APPROVED** [review]
Hey Kathy,

Thank you for this code! From the looks of it, you've added a docker-compose command to the create-test-database.  Grateful it's there, just recently overcame an dev environment issue regarding docker-compose.

The BulkSendButton, is there additional instructions that need to be added to the documentation for how that feature works?  Maybe a HOWTO_BULK_SEND?  That would be the last piece that I think is missing in this pull request.

**Comment by crayolakat** [comment]
@Arique1104 There is a page called `HOWTO-use_bulk_sending`, does that work? [HOWTO-use_bulk_sending](https://statevoicesnational.github.io/Spoke/#/HOWTO-use_bulk_sending)

**Comment by crayolakat** [comment]
Closing in favor of https://github.com/StateVoicesNational/Spoke/pull/2332, which is based off the all-emcompassing MoveOn `main` branch

**Pull request closed without merging**
