### PR TITLE
Upgrade cypress from 5.6.0 to 13.11.0

### PR DESCRIPTION
**Pull request by stefanhayden**
# Fixes # (issue)

## Description

upgrade cypress library

_Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change, and any blockers that make your change a WIP_

# Checklist:

- [ ] I have manually tested my changes on desktop and mobile
- [x] The test suite passes locally with my changes
- [ ] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [ ] [My change is 300 lines of code or less](https://github.com/StateVoicesNational/Spoke/blob/main/CONTRIBUTING.md#submitting-your-pull-request), or has a documented reason in the description why it’s longer
- [ ] I have made any necessary changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] My PR is labeled [WIP] if it is in progress

### CODE REVIEW

**Comment by engelhartrueben** [comment]
Once we get the 14.1 branch created, we will review and merge.
Thank you for working on this!

**Comment by engelhartrueben** [comment]
Hey @stefanhayden,
Can you rebase this to get up to date with `stage-main-14.1`?

**Comment by stefanhayden** [comment]
@engelhartrueben rebased!

**Comment by mau11** [comment]
~thanks @stefanhayden for working on this! it looks like there are some merge conflicts since you last rebased (I apologize for the delay on getting this merged in), aside from that, it looks good to go!~ 

the conflicts have disappeared 🪄 thanks for working on this @stefanhayden!

**Review by mau11 — APPROVED** [review]

**Pull request merged**
